scanr-patents:
  schema: scanr-patents.json
  annotation: scanr-patents.yaml
  content: "Patents filed by French research institutions. One document is one patent."
  primary_fields:
    - id
    - inpadocFamily
    - title.default
    - summary.default
    - year
    - type
    - isOeb
    - isOa
    - isInternational
    - productionType
    - inventionKind
    - applicants.name
    - applicants.type
    - applicants.country
    - applicants.ids.id
    - applicants.ids.type
  cross_refs:
    applicants.ids.id:
      index: scanr-organizations
      join_field: id
