scanr-publications:
  schema: scanr-publications.json
  annotation: scanr-publications.yaml
  content: Scientific publications (articles, theses, conference papers). One document is one publication.
  primary_fields:
    - id
    - title.default
    - summary.default
    - year
    - type
    - productionType
    - isOa
    - authors.fullName
    - authors.person
    - authorsCount
    - affiliations.id
    - externalIds.type
    - externalIds.id
    - source.title
    - source.journalIssns
    - keywords.default
    - domains.label.default
  excludes:
    - title.*
  includes:
    - title.default
    - title.en
    - title.fr
  cross_refs:
    authors.person:
      index: scanr-persons
      join_field: id
    affiliations.id:
      index: scanr-organizations
      join_field: id
    authors.affiliations.id:
      index: scanr-organizations
      join_field: id
  resolve:
    search_fields:
      - title.*
    source_fields:
      - title.default
