scanr-participations:
  schema: scanr-participations.json
  annotation: scanr-participations.yaml
  content: "Projects participations by organizations. One document is one project participation by an organization."
  primary_fields:
    - participant_id
    - participant_kind
    - participant_type
    - participant_label.fr
    - participant_label.en
    - participant_acronym.default
    - participant_status
    - participation_id
    - project_id
    - project_type
    - project_year
    - project_action
    - project_label
  cross_refs:
    participant_id:
      index: scanr-organizations
      join_field: id
    project_id:
      index: scanr-projects
      join_field: id