SCHEMAS_FOLDER = "schemas"
ANNOTATIONS_FOLDER = "annotations"

SCANR_INDEXES = {
    "scanr-publications": {
        "schema": "scanr_publications.json",
        "annotation": "scanr_publications.yaml",
        "content": "This index stores scientific publications (journal articles, theses, conference papers, preprints) aggregated from HAL, PubMed, and Crossref. Each document represents one production with its bibliographic metadata, authors, affiliations, and more.",
        "primary_fields": [
            "id",
            "title.default",
            "year",
            "type",
            "isOa",
            "authors.fullName",
            "authors.role",
            "externalIds.type",
            "externalIds.id",
            "source.title",
            "source.issn",
            "domains",
        ],
        "excludes": ["title.*"],
        "includes": ["title.default", "title.en", "title.fr"],
    },
    "scanr-organizations": {
        "schema": "scanr_organizations.json",
        "annotation": "scanr_organizations.yaml",
        "content": "This index stores scientific organizations (universities, research institutions, companies) that appear in the research ecosystem.",
        "primary_fields": ["id", "name", "type", "country", "city", "domains"],
    },
    "scanr-persons": {
        "schema": "scanr_persons.json",
        "annotation": "scanr_persons.yaml",
        "content": "This index stores scientific persons (researchers, authors, etc.) that appear in the research ecosystem.",
        "primary_fields": ["id", "fullName", "role", "email", "domains"],
    },
    "scanr-patents": {
        "schema": "scanr_patents.json",
        "annotation": "scanr_patents.yaml",
        "content": "This index stores scientific patents (journal articles, theses, conference papers, preprints) aggregated from HAL, PubMed, and Crossref. Each document represents one production with its bibliographic metadata, authors, affiliations, and open-access status.",
        "primary_fields": [
            "id",
            "title",
            "year",
            "type",
            "isOa",
            "authors.fullName",
            "authors.role",
            "externalIds.type",
            "externalIds.id",
            "source.title",
            "source.issn",
            "domains",
        ],
    },
    "scanr-projects": {
        "schema": "scanr_projects.json",
        "annotation": "scanr_projects.yaml",
        "content": "This index stores scientific projects (journal articles, theses, conference papers, preprints) aggregated from HAL, PubMed, and Crossref. Each document represents one production with its bibliographic metadata, authors, affiliations, and open-access status.",
        "primary_fields": [
            "id",
            "title",
            "year",
            "type",
            "isOa",
            "authors.fullName",
            "authors.role",
            "externalIds.type",
            "externalIds.id",
            "source.title",
            "source.issn",
            "domains",
        ],
    },
    "scanr-participations": {
        "schema": "scanr_participations.json",
        "annotation": "scanr_participations.yaml",
        "content": "This index stores scientific participations (journal articles, theses, conference papers, preprints) aggregated from HAL, PubMed, and Crossref. Each document represents one production with its bibliographic metadata, authors, affiliations, and open-access status.",
        "primary_fields": [
            "id",
            "title",
            "year",
            "type",
            "isOa",
            "authors.fullName",
            "authors.role",
            "externalIds.type",
            "externalIds.id",
            "source.title",
            "source.issn",
            "domains",
        ],
    },
}
